# Generated by Django 5.1.4 on 2024-12-10 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField(help_text='2020')),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('critico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app_coder.critico')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app_coder.libro')),
            ],
        ),
    ]
